### ISSUE TITLE
Weird artifacts

### ISSUE THREAD

**Issue by Famazoo** [bozbez/tm3-mod-exporter#1]
hi, weird artifacts appear on Details_I when i convert my textures with the tool. 
Heres how it looks like with stupskiesels tool:
![oldtool](https://user-images.githubusercontent.com/37294929/154860578-cc3684e7-6d12-4164-8a0a-6a4269e5d6ba.png)

This is with the new tool:
![newtool](https://user-images.githubusercontent.com/37294929/154860614-524d1fe8-954d-468c-bd4f-07ab7a4a5fc4.png)

My settings:
- Archive, Car Skin, 4096px

**Comment by bozbez** [comment]
Could you attach the input folder you are observing this with as well as the output skin archive you are getting from the tool and the expected output?

**Comment by Famazoo** [comment]
Have sent it privatly

**Comment by bozbez** [comment]
Seems this was an issue with the game generating its own mipmaps for car skins when you upload, and it was stacking all of the tool exported mipmaps together before doing that.

Fixed in ab5add1217923f6afb88b8cc77dec5617fbd6f07, there is now an option to disable tool mipmap generation, set by default for the car skin mode.
